### ISSUE TITLE
Input type text, Firefox, value invisible

### ISSUE THREAD

**Issue by tcrowe** [InkSpeck/fluidity#7]
The text box control looks consistent with other browser but the value and cursor do not show up.

Here's what I did as a temporary workaround:
```
input[type=text]
	height 100%
	padding 0.4em
```

With the workaround input type text does not have a consistent appearance but the text and cursor become visible.

I tested this in Firefox v29 & v30.

**Comment by InkSpeck** [comment]
Sorry it took so long to get this fixed. Please check it out in the latest release if you get a chance. I've overhauled the forms styles and made them a lot simpler.

**Comment by tcrowe** [comment]
Thanks bud. I'll do some more implementations and see how it goes. ;]
